/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"c-cpp-project-template"
#define VCS_UUID		"69c80dcec686f0c6a50032f11b026cc1004acd04"
#define VCS_NUM			43
#define VCS_DATE		"2021-04-11T02:19:27Z"
#define VCS_BRANCH		"next"
#define VCS_TAG			""
#define VCS_TAG_OPENPGP	""
#define VCS_TICK		43
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2021-04-11T02:19:27Z!103922926@qq.com"
#define VCS_FULL_HASH		"6b58cc0d1dcf4b3643051388e70c81310ca8b99e"
#define VCS_COMMIT_OPENPGP	""
#define VCS_SHORT_HASH		"6b58cc0"

#define VCS_WC_MODIFIED		1

#endif

/* end */
