message("External project: cJSON")

ExternalProject_Add(cJSON
    GIT_REPOSITORY https://github.com/DaveGamble/cJSON.git
    GIT_TAG "v1.7.8"
    BUILD_IN_SOURCE 1
    CMAKE_ARGS += -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> 
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} 
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} 
    -DBUILD_DOC=OFF
    -DBUILD_DOCS=OFF
    -DBUILD_EXAMPLE=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TEST=OFF
    -DBUILD_TESTS=OFF 
    -DBUILD_TESTING=OFF 
)