message("External project: jsoncpp")
if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 7.0)
    set(JSONCCP_EXTRA_FLAGS -Wno-implicit-fallthrough)
else()
    set(JSONCCP_EXTRA_FLAGS "")
endif()

ExternalProject_Add(jsoncpp
    URL https://github.com/open-source-parsers/jsoncpp/archive/1.7.7.tar.gz
    URL_HASH SHA256=087640ebcf7fbcfe8e2717a0b9528fff89c52fcf69fa2a18cc2b538008098f97
    CMAKE_ARGS += -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR> 
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER} 
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} 
    -DBUILD_DOC=OFF
    -DBUILD_DOCS=OFF
    -DBUILD_EXAMPLE=OFF
    -DBUILD_EXAMPLES=OFF
    -DBUILD_TEST=OFF
    -DBUILD_TESTS=OFF 
    -DBUILD_TESTING=OFF 
    -DWITH_WEBSOCKETS=OFF
    -DJSONCPP_WITH_TESTS=OFF
    -DCMAKE_CXX_FLAGS=${JSONCCP_EXTRA_FLAGS}
)